# Generated by Django 4.2 on 2023-04-13 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainOffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post')),
                ('date', models.DateTimeField()),
                ('group', models.ForeignKey(db_column='group', on_delete=django.db.models.deletion.CASCADE, to='MainOffice.groupforlead')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
                'managed': True,
            },
        ),
    ]
