# Generated by Django 4.2 on 2023-04-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainOffice', '0004_task_сustomer_alter_sms_date_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
